FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

# Set working directory
WORKDIR /basic-project

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . .